In [38]:
import os
import pandas as pd
os.chdir('./../')

In [2]:
import datasets
data = datasets.load_dataset("nirschl-lab/acevedo_et_al_2020")

/home/wisc/maheswararao/code/lightning-hydra-template/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# resnet_predictions = 'notebooks/wbc-challenge/acevedo.csv'
# resent_df = pd.read_csv(resnet_predictions)
# resent_df.head()
# resent_df.rename(columns={'labels': 'prediction'}, inplace=True)
# resent_df['label'] = None
# classes_to_idx = eval(item['classes_to_idx'])
# idx_to_class = {v: k for k, v in classes_to_idx.items()}
# resent_df['label_name'] = resent_df['label'].map(idx_to_class)

In [47]:
acevedo_data = {'file_name': [], 'label': [], 'fold': []}

In [49]:
for item in data['train']:
    file_name = item['filename']
    label_name = item['label_name']
    acevedo_data['file_name'].append(file_name)
    acevedo_data['label'].append(label_name)
    acevedo_data['fold'].append('train')

In [50]:
for item in data['validation']:
    file_name = item['filename']
    label_name = item['label_name']
    acevedo_data['file_name'].append(file_name)
    acevedo_data['label'].append(label_name)
    acevedo_data['fold'].append('validation')

In [51]:
for item in data['test']:
    file_name = item['filename']
    label_name = item['label_name']
    acevedo_data['file_name'].append(file_name)
    acevedo_data['label'].append(label_name)
    acevedo_data['fold'].append('test')

In [46]:
item['filename']

'13314_f2d2b469_na_split-validation_neutrophil.png'

In [52]:
acevedo_total_csv = pd.DataFrame(acevedo_data)

In [ ]:
acevedo_total_csv

In [30]:
# acevedo_total_csv.head()
len(acevedo_total_csv)

17092

In [53]:
acevedo_total_csv.head()

                                        file_name         label   fold
0    07940_e877e535_na_split-train_neutrophil.png    neutrophil  train
1    10603_03ae2418_na_split-train_neutrophil.png    neutrophil  train
2  00406_5367f292_na_split-train_erythroblast.png  erythroblast  train
3  05606_09d93090_na_split-train_erythroblast.png  erythroblast  train
4    07490_5eaf7bd5_na_split-train_neutrophil.png    neutrophil  train

In [54]:
#subset dataset where lablel=basophil, eosinophil, monocyte
acevedo_wbc_subset = acevedo_total_csv[acevedo_total_csv['label'].isin(['basophil', 'eosinophil', 'monocyte'])]

In [55]:
#remane column label to acevedo_label
acevedo_wbc_subset.rename(columns={'label': 'acevedo_label'}, inplace=True)

/tmp/ipykernel_4032481/3377742644.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acevedo_wbc_subset.rename(columns={'label': 'acevedo_label'}, inplace=True)

In [56]:
# print(len(acevedo_wbc_subset))
# print(acevedo_wbc_subset['acevedo_label'].value_counts())
# acevedo_wbc_subset.head()
#map to wbc labels
wbc_map = {'basophil': 'BA', 'eosinophil': 'EO', 'monocyte': 'MO'}
acevedo_wbc_subset['labels'] = acevedo_wbc_subset['acevedo_label'].map(wbc_map)

/tmp/ipykernel_4032481/2130811267.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acevedo_wbc_subset['labels'] = acevedo_wbc_subset['acevedo_label'].map(wbc_map)

In [57]:
acevedo_wbc_subset.head()

                                       file_name acevedo_label   fold labels
5   03441_b3e9af60_na_split-train_eosinophil.png    eosinophil  train     EO
10  01846_d756e121_na_split-train_eosinophil.png    eosinophil  train     EO
12    08350_f793e208_na_split-train_monocyte.png      monocyte  train     MO
13    03285_0e90df57_na_split-train_basophil.png      basophil  train     BA
17    02351_40198a1e_na_split-train_basophil.png      basophil  train     BA

In [42]:
(acevedo_wbc_subset['fold'].value_counts())

fold
train         4023
test          1151
validation     581
Name: count, dtype: int64

In [58]:
acevedo_wbc_subset.to_csv('data/wbc/acevedo_wbc_subset.csv')

In [30]:
prediction_full_names = {'SNE' : 'Segmented neutrophil',
'LY' : 'Lymphocyte',
'MO': 'Monocyte',
'EO' : 'Eosinophil',
'BA' : 'Basophil',
'VLY' : 'Variant (atypical) lymphocyte',
'BNE' : 'Band-form neutrophil',
'MMY' : 'Metamyelocyte',
'MY' : 'Myelocyte',
'PMY' : 'Promyelocyte',
'BL' : 'Blast cell',
'PC' : 'Plasma cell',
'PLY' : 'Prolymphocyte'
}

In [10]:
# resent_df.isna().any()
# resent_df.isnull().any()
# eval(item['classes_to_idx'])

In [27]:
item

{'image_id': 'f2d2b469-2cf1-4ad9-bb85-8a902f7afbc6',
 'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=360x360>,
 'label': 6,
 'label_name': 'neutrophil',
 'dataset': None,
 'domain': 'pathology',
 'institution': 'hosp_barcelona',
 'license': 'CC-BY-4.0',
 'microns_per_pixel': 0.10000000149011612,
 'modality': 'light microscopy',
 'ncbitaxon_id': 'NCBITaxon_9606',
 'ncbitaxon_name': 'Homo sapiens',
 'pmid': '32346559',
 'split': 'validation',
 'stain': 'Giemsa',
 'subdomain': 'hematopathology',
 'submodality': 'brightfield microscopy',
 'synthetic': False,
 'bto_id': 'BTO_0003473',
 'bto_name': 'neutrophil',
 'cellontology_id': 'CL_0000096',
 'cellontology_name': 'neutrophil',
 'classes_to_idx': "{'basophil': 0, 'eosinophil': 1, 'erythroblast': 2, 'immature_granulocyte': 3, 'lymphocyte': 4, 'monocyte': 5, 'neutrophil': 6, 'platelet': 7}",
 'comment': None,
 'dataset_name': 'acevedo_et_al_2020',
 'dataset_slug': 'acevedo_et_al_2020',
 'dataset_parent': None,
 'filename': '13314_f2d2b469_na_split-validation_neutrophil.png',
 'file_size': 124058,
 'fma_id': None,
 'fma_name': None,
 'instance_count': None,
 'image_md5': 'fdd3707dd3e05441d8224f6491456fe6',
 'label_task': 'white blood cell classification',
 'label_additional_info': 'Neutrophils are also capable of secreting GRO-alpha, IL-1beta, IL-1ra, IL-3, IL-12, IP-10, MIG, MIP-1alpha, MIP-1beta, TGF-beta, TNF-alpha, VEGF, and anti-microbial peptides. They can positively influence the chemotaxis of basophils, T-cells, monocytes, macrophages, dendritic cells, and other neutrophils. Neutrophils are also CD35-positive, CD64-positive, CD89-positive, CD184-positive, and fMLP receptor-positive Ly-6G-positive (mouse), TLR2-low, TLR4-low, and lineage-negative (CD2, CD3, CD5, CD9, CD19, CD36, CD49d, CD56, CD61, CD235a (glycophorin-A)).',
 'label_description': 'A fully differentiated neutrophil, a granular leukocyte having a nucleus with three to five lobes connected by slender threads, and cytoplasm containing fine inconspicuous granules and stainable by neutral dyes. They are produced in bone marrow at a rate of 5e10-10e10/day and have a half-life of 6-8 hours. Neutrophils are CD15-positive, CD16-positive, CD32-positive, CD43-positive, CD181-positive, and CD182-positive.',
 'label_synonyms': "['PMN', 'polymorphonuclear neutrophil', 'mature neutrocyte', 'mature neutrophilic leukocyte', 'polymorphonuclear leukocyte', 'mature neutrophil', 'poly', 'polynuclear neutrophilic leukocyte', 'mature neutrophil leucocyte', 'mature neutrophilic leucocyte', 'mature neutrophil leukocyte', 'polymorphonuclear leucocyte', 'polynuclear neutrophilic leucocyte']",
 'last_updated': '2024-09-19T03:46:30.112Z',
 'loinc_id': 'LOINC_58407-8',
 'mesh_id': None,
 'mesh_name': None,
 'ncit_id': "['NCIT_C79903', 'NCIT_C35655']",
 'normal_or_abnormal': 'normal',
 'original_filename': 'SNE_672698.jpg',
 'phash': 'e68a8d6623bcda6c',
 'snomedct_id': 'SCTID_737535000',
 'supported_tasks': 'multi_class',
 'caption': None}