In [1]:
import os
os.chdir('./../')

In [2]:
import pandas as pd

In [16]:
csv_path = 'csv/elena'
# ADRCparticipants = pd.read_csv(os.path.join(csv_path, '20251106_allADRCparticipants.csv'))
# WRAPparticipants = pd.read_csv(os.path.join(csv_path, '20251106_allWRAPparticipants.csv'))
allWBDPparticipants = pd.read_csv(os.path.join(csv_path, '20251106_allWBDPparticipants.csv')) #all pple signed up for brain donar program
MK6240WRAP = pd.read_csv(os.path.join(csv_path, '20251106_MK6240WRAP.csv')) # who have had PET scan in WRAP
MK6240ADRC = pd.read_csv(os.path.join(csv_path, '20251106_MK6240ADRC.csv')) # who have had PET scan in ADRC

In [23]:
# allWBDPparticipants.head()
# ADRCparticipants.head()
# WRAPparticipants.head()
print(len(allWBDPparticipants['id'].unique()))
print(len(MK6240WRAP['reggieid'].unique()))

1182
735

In [27]:
# all unique 'reggieid' in MK6240WRAP that are not in allWBDPparticipants 'id', remove duplicates

MK6240WRAP[~MK6240WRAP['reggieid'].isin(allWBDPparticipants['id'])].drop_duplicates(subset=['reggieid']).to_csv(os.path.join(csv_path, '20251106_MK6240WRAP_notin_WBDPparticipants.csv'), index=False)
# len(MK6240WRAP[~MK6240WRAP['reggieid'].isin(allWBDPparticipants['id'])])

In [28]:
#for adrc
MK6240ADRC[~MK6240ADRC['reggieid'].isin(allWBDPparticipants['id'])].drop_duplicates(subset=['reggieid']).to_csv(os.path.join(csv_path, '20251106_MK6240ADRC_notin_WBDPparticipants.csv'), index=False)

In [18]:
# MK6240ADRC.head()
# MK6240WRAP.head()
allWBDPparticipants.head()

     id
0  1241
1  1245
2  1253
3  1258
4  1272

In [13]:
print(len(WRAPparticipants)) 
print(len(MK6240WRAP))

1182
1271

In [ ]:
# what 'reggieid' in MK6240WRAP are not in WRAPparticipants 'id'?

      reggieid
0         3741
1         3741
2         3741
3         3887
4         3887
...        ...
1265     18274
1266     18330
1267     18599
1268     13861
1269     18444

[557 rows x 1 columns]